<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PHP2000-Quiz2-Collaborations</title>
</head>
<body>
    <form action="colaborar" method="POST">
        <div>
            <select name="versions">

                <?php foreach($colab as $c){?>

                    <option value=""> <?php echo "$c->ip | $c->inserted"?></option>
                    
                <?php }?>

            </select>
        </div>
                    <br>
        <div>
            <textarea name="colaboraciones" cols="100" rows="25"><?= $colab[0]->colaborac;?></textarea>
        </div>

        <div>
            <button type="submit">Colaborate with Joy!</button>
        </div>
    </form>
       

</body>
</html>